package errortype

const (
	INTERNAL_CONNECTION_PROBLEM = "INTERNAL_CONNECTION_PROBLEM"
	INTERNAL_SERVER_ERROR       = "INTERNAL_SERVER_ERROR"
	INVALID_SCOPE               = "INVALID_SCOPE"
	WRONG_PASSWORD              = "WRONG_PASSWORD"
	WRONG_USERNAME              = "WRONG_USERNAME"
	USER_NOT_FOUND              = "USER_NOT_FOUND"
	WRONG_EMAIL_FORMAT          = "WRONG_EMAIL_FORMAT"
	INVALID_PASSWORD_FORMAT     = "INVALID_PASSWORD_FORMAT"
	VALIDATION_FAILED           = "VALIDATION_FAILED"
	AUTHENTICATION_FAILED       = "AUTHENTICATION_FAILED"
	INVALID_INPUT               = "INVALID_INPUT"
)